security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/agences$, roles: ROLE_ADMIN, methods: [POST] }
        - { path: ^/api/agences$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/agences/villes$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/vehicules$, roles: ROLE_ADMIN, methods: [POST] }
        - { path: ^/api/vehicules$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/vehicules/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/vehicules/\d+$, roles: ROLE_ADMIN, methods: [DELETE] }
        - { path: ^/api/vehicules/search, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/users$, roles: ROLE_ADMIN, methods: [GET] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
