version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh:ro # Remonte la clé SSH dans le devcontainer
      - ../:/workspace
      - ../frontend/.env:/workspace/frontend/.env:ro
    ports:
      - "127.0.0.1:8000:8000"  # Symfony
      - "127.0.0.1:5173:5173"  # Vite
    command: bash -c "cd backend && php -S 0.0.0.0:8000 -t public"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goride
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - db
volumes:
  dbdata:
